# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_V02tcAAat.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        if not Calculator.objectName():
            Calculator.setObjectName(u"Calculator")
        Calculator.resize(543, 716)
        self.Button_Dot = QPushButton(Calculator)
        self.Button_Dot.setObjectName(u"Button_Dot")
        self.Button_Dot.setGeometry(QRect(170, 520, 75, 75))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.Button_Dot.setFont(font)
        self.Button_3 = QPushButton(Calculator)
        self.Button_3.setObjectName(u"Button_3")
        self.Button_3.setGeometry(QRect(300, 420, 75, 75))
        self.Button_3.setFont(font)
        self.Button_5 = QPushButton(Calculator)
        self.Button_5.setObjectName(u"Button_5")
        self.Button_5.setGeometry(QRect(170, 320, 75, 75))
        self.Button_5.setFont(font)
        self.Button_7 = QPushButton(Calculator)
        self.Button_7.setObjectName(u"Button_7")
        self.Button_7.setGeometry(QRect(40, 210, 75, 75))
        self.Button_7.setFont(font)
        self.Button_9 = QPushButton(Calculator)
        self.Button_9.setObjectName(u"Button_9")
        self.Button_9.setGeometry(QRect(300, 210, 75, 75))
        self.Button_9.setFont(font)
        self.Button_0 = QPushButton(Calculator)
        self.Button_0.setObjectName(u"Button_0")
        self.Button_0.setGeometry(QRect(40, 520, 75, 75))
        self.Button_0.setFont(font)
        self.Button_6 = QPushButton(Calculator)
        self.Button_6.setObjectName(u"Button_6")
        self.Button_6.setGeometry(QRect(300, 320, 75, 75))
        self.Button_6.setFont(font)
        self.Button_4 = QPushButton(Calculator)
        self.Button_4.setObjectName(u"Button_4")
        self.Button_4.setGeometry(QRect(40, 320, 75, 75))
        self.Button_4.setFont(font)
        self.Button_2 = QPushButton(Calculator)
        self.Button_2.setObjectName(u"Button_2")
        self.Button_2.setGeometry(QRect(170, 420, 75, 75))
        self.Button_2.setFont(font)
        self.Button_Delete = QPushButton(Calculator)
        self.Button_Delete.setObjectName(u"Button_Delete")
        self.Button_Delete.setGeometry(QRect(300, 520, 75, 75))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(20)
        font1.setBold(True)
        font1.setWeight(75)
        self.Button_Delete.setFont(font1)
        self.Button_8 = QPushButton(Calculator)
        self.Button_8.setObjectName(u"Button_8")
        self.Button_8.setGeometry(QRect(170, 210, 75, 75))
        self.Button_8.setFont(font)
        self.Button_1 = QPushButton(Calculator)
        self.Button_1.setObjectName(u"Button_1")
        self.Button_1.setGeometry(QRect(40, 420, 75, 75))
        self.Button_1.setFont(font)
        self.Button_LeftBracket = QPushButton(Calculator)
        self.Button_LeftBracket.setObjectName(u"Button_LeftBracket")
        self.Button_LeftBracket.setGeometry(QRect(170, 100, 75, 75))
        self.Button_LeftBracket.setFont(font)
        self.Button_RightBracket = QPushButton(Calculator)
        self.Button_RightBracket.setObjectName(u"Button_RightBracket")
        self.Button_RightBracket.setGeometry(QRect(300, 100, 75, 75))
        self.Button_RightBracket.setFont(font)
        self.Button_AC = QPushButton(Calculator)
        self.Button_AC.setObjectName(u"Button_AC")
        self.Button_AC.setGeometry(QRect(40, 100, 75, 75))
        self.Button_AC.setFont(font)
        self.Button_Times = QPushButton(Calculator)
        self.Button_Times.setObjectName(u"Button_Times")
        self.Button_Times.setGeometry(QRect(430, 210, 75, 75))
        self.Button_Times.setFont(font)
        self.Button_Divide = QPushButton(Calculator)
        self.Button_Divide.setObjectName(u"Button_Divide")
        self.Button_Divide.setGeometry(QRect(430, 100, 75, 75))
        self.Button_Divide.setFont(font)
        self.Button_Minus = QPushButton(Calculator)
        self.Button_Minus.setObjectName(u"Button_Minus")
        self.Button_Minus.setGeometry(QRect(430, 320, 75, 75))
        self.Button_Minus.setFont(font)
        self.Button_Add = QPushButton(Calculator)
        self.Button_Add.setObjectName(u"Button_Add")
        self.Button_Add.setGeometry(QRect(430, 420, 75, 75))
        self.Button_Add.setFont(font)
        self.Button_Equal = QPushButton(Calculator)
        self.Button_Equal.setObjectName(u"Button_Equal")
        self.Button_Equal.setGeometry(QRect(430, 520, 75, 75))
        self.Button_Equal.setFont(font)
        self.Formula_Text = QTextEdit(Calculator)
        self.Formula_Text.setObjectName(u"Formula_Text")
        self.Formula_Text.setGeometry(QRect(40, 16, 465, 71))
        font2 = QFont()
        font2.setPointSize(22)
        font2.setBold(False)
        font2.setWeight(50)
        self.Formula_Text.setFont(font2)
        self.Formula_Text.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Formula_Text.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.Formula_Text.setLineWrapMode(QTextEdit.NoWrap)
        self.Formula_Text.setReadOnly(True)
        self.Result_Text = QTextEdit(Calculator)
        self.Result_Text.setObjectName(u"Result_Text")
        self.Result_Text.setEnabled(True)
        self.Result_Text.setGeometry(QRect(40, 620, 465, 51))
        self.Result_Text.setFont(font2)
        self.Result_Text.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Result_Text.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Result_Text.setReadOnly(True)
        self.label_6 = QLabel(Calculator)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 680, 411, 31))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setItalic(True)
        font3.setWeight(75)
        self.label_6.setFont(font3)
        self.label_6.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)

        self.retranslateUi(Calculator)

        QMetaObject.connectSlotsByName(Calculator)
    # setupUi

    def retranslateUi(self, Calculator):
        Calculator.setWindowTitle(QCoreApplication.translate("Calculator", u"Calculator", None))
        self.Button_Dot.setText(QCoreApplication.translate("Calculator", u".", None))
#if QT_CONFIG(shortcut)
        self.Button_Dot.setShortcut(QCoreApplication.translate("Calculator", u".", None))
#endif // QT_CONFIG(shortcut)
        self.Button_3.setText(QCoreApplication.translate("Calculator", u"3", None))
#if QT_CONFIG(shortcut)
        self.Button_3.setShortcut(QCoreApplication.translate("Calculator", u"3", None))
#endif // QT_CONFIG(shortcut)
        self.Button_5.setText(QCoreApplication.translate("Calculator", u"5", None))
#if QT_CONFIG(shortcut)
        self.Button_5.setShortcut(QCoreApplication.translate("Calculator", u"5", None))
#endif // QT_CONFIG(shortcut)
        self.Button_7.setText(QCoreApplication.translate("Calculator", u"7", None))
#if QT_CONFIG(shortcut)
        self.Button_7.setShortcut(QCoreApplication.translate("Calculator", u"7", None))
#endif // QT_CONFIG(shortcut)
        self.Button_9.setText(QCoreApplication.translate("Calculator", u"9", None))
#if QT_CONFIG(shortcut)
        self.Button_9.setShortcut(QCoreApplication.translate("Calculator", u"9", None))
#endif // QT_CONFIG(shortcut)
        self.Button_0.setText(QCoreApplication.translate("Calculator", u"0", None))
#if QT_CONFIG(shortcut)
        self.Button_0.setShortcut(QCoreApplication.translate("Calculator", u"0", None))
#endif // QT_CONFIG(shortcut)
        self.Button_6.setText(QCoreApplication.translate("Calculator", u"6", None))
#if QT_CONFIG(shortcut)
        self.Button_6.setShortcut(QCoreApplication.translate("Calculator", u"6", None))
#endif // QT_CONFIG(shortcut)
        self.Button_4.setText(QCoreApplication.translate("Calculator", u"4", None))
#if QT_CONFIG(shortcut)
        self.Button_4.setShortcut(QCoreApplication.translate("Calculator", u"4", None))
#endif // QT_CONFIG(shortcut)
        self.Button_2.setText(QCoreApplication.translate("Calculator", u"2", None))
#if QT_CONFIG(shortcut)
        self.Button_2.setShortcut(QCoreApplication.translate("Calculator", u"2", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Delete.setText(QCoreApplication.translate("Calculator", u"\u232b", None))
#if QT_CONFIG(shortcut)
        self.Button_Delete.setShortcut(QCoreApplication.translate("Calculator", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.Button_8.setText(QCoreApplication.translate("Calculator", u"8", None))
#if QT_CONFIG(shortcut)
        self.Button_8.setShortcut(QCoreApplication.translate("Calculator", u"8", None))
#endif // QT_CONFIG(shortcut)
        self.Button_1.setText(QCoreApplication.translate("Calculator", u"1", None))
#if QT_CONFIG(shortcut)
        self.Button_1.setShortcut(QCoreApplication.translate("Calculator", u"1", None))
#endif // QT_CONFIG(shortcut)
        self.Button_LeftBracket.setText(QCoreApplication.translate("Calculator", u"(", None))
#if QT_CONFIG(shortcut)
        self.Button_LeftBracket.setShortcut(QCoreApplication.translate("Calculator", u"(", None))
#endif // QT_CONFIG(shortcut)
        self.Button_RightBracket.setText(QCoreApplication.translate("Calculator", u")", None))
#if QT_CONFIG(shortcut)
        self.Button_RightBracket.setShortcut(QCoreApplication.translate("Calculator", u")", None))
#endif // QT_CONFIG(shortcut)
        self.Button_AC.setText(QCoreApplication.translate("Calculator", u"AC", None))
#if QT_CONFIG(shortcut)
        self.Button_AC.setShortcut(QCoreApplication.translate("Calculator", u"A, C", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Times.setText(QCoreApplication.translate("Calculator", u"\u00d7", None))
#if QT_CONFIG(shortcut)
        self.Button_Times.setShortcut(QCoreApplication.translate("Calculator", u"*", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Divide.setText(QCoreApplication.translate("Calculator", u"\u00f7", None))
#if QT_CONFIG(shortcut)
        self.Button_Divide.setShortcut(QCoreApplication.translate("Calculator", u"/", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Minus.setText(QCoreApplication.translate("Calculator", u"-", None))
#if QT_CONFIG(shortcut)
        self.Button_Minus.setShortcut(QCoreApplication.translate("Calculator", u"-", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Add.setText(QCoreApplication.translate("Calculator", u"+", None))
#if QT_CONFIG(shortcut)
        self.Button_Add.setShortcut(QCoreApplication.translate("Calculator", u"+", None))
#endif // QT_CONFIG(shortcut)
        self.Button_Equal.setText(QCoreApplication.translate("Calculator", u"=", None))
        self.Formula_Text.setHtml(QCoreApplication.translate("Calculator", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'PMingLiU'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Result_Text.setHtml(QCoreApplication.translate("Calculator", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'PMingLiU'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("Calculator", u"Developed by WillyF", None))
    # retranslateUi

